# Ko configuration for container images ONLY
# https://ko.build/configuration/

# Distroless base for minimal attack surface and security
defaultBaseImage: gcr.io/distroless/static-debian12:nonroot

# Build settings matching GoReleaser optimization
builds:
  - id: homeddns
    dir: .
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - -s -w
      - -extldflags=-static
      - -X github.com/markussiebert/homeddns.buildVersion={{.Env.VERSION}}
      - -X github.com/markussiebert/homeddns.buildDate={{.Env.BUILD_DATE}}
      - -X github.com/markussiebert/homeddns.buildCommit={{.Env.GIT_COMMIT}}

# Multi-platform support
platforms:
  - linux/amd64
  - linux/arm64
  - linux/arm/v7

# OCI metadata labels (follows OCI Image Spec)
# https://github.com/opencontainers/image-spec/blob/main/annotations.md
labels:
  org.opencontainers.image.title: homeddns
  org.opencontainers.image.description: Dynamic DNS update daemon for AWS Route53 and Netcup
  org.opencontainers.image.vendor: Markus Siebert
  org.opencontainers.image.licenses: MIT
  org.opencontainers.image.source: https://github.com/markussiebert/homeddns
  org.opencontainers.image.url: https://github.com/markussiebert/homeddns
  org.opencontainers.image.documentation: https://github.com/markussiebert/homeddns/blob/main/README.md
  # Home Assistant add-on labels
  io.hass.name: "HomeDDNS"
  io.hass.description: "Self-hosted Dynamic DNS service"
  io.hass.type: "addon"
